services:
  - type: web
    name: enterprise-rag-api
    env: docker
    dockerfilePath: Dockerfile
    region: singapore
    plan: free
    dockerCommand: uvicorn app.main:app --host 0.0.0.0 --port 8080
    envVars:
      - key: STRICT_STARTUP
        value: "false"
      - key: LOGFIRE_IGNORE_NO_CONFIG
        value: "1"

  - type: web
    name: enterprise-rag-ui
    env: docker
    dockerfilePath: Dockerfile
    region: singapore
    plan: free
    dockerCommand: streamlit run ui/app.py --server.port 8501 --server.address 0.0.0.0
    envVars:
      - key: LOGFIRE_IGNORE_NO_CONFIG
        value: "1"
